Repository wellcometrust/reach, pull requests merged in 2020-06, with the labels that each got.

#552 Updated GH endpoint
  web/web/views/contact.py
Labels: enhancement

#560 Search updates - #557 #558
  web/web/views/api/api_search_citations.py
  web/web/views/api/api_search_policies.py
Labels: Bug, enhancement

#561 Fix pagination and sorting in JS
  web/web/src/js/citationsTable.js
  web/web/src/js/policyTable.js
  web/web/src/js/resultsCommon.js
  web/web/templates/results/citations.html
  web/web/templates/results/policy-docs.html
  web/web/views/api/api_search_citations.py
  web/web/views/api/api_search_policies.py
Labels: Bug, Engineering

#567 Fuzzymatcher Output Fix
  pipeline/reach-fuzzy-matcher/fuzzymatcher_task.py
Labels: Bug

#581 Fixes issues in IE11 with Symbol and for (let x of y) {...} convernience
  web/.babelrc
  web/.eslintrc.json
  web/gulpfile.js
  web/gulpfile.local.js
  web/package-lock.json
  web/package.json
  web/web/src/js/app.js
  web/web/src/js/citationsTable.js
  web/web/src/js/policyTable.js
  web/web/src/js/templates/no_results.js
  web/web/templates/base.html
Labels: Bug
