Repository wellcometrust/reach, pull requests merged in 2020-01, with the labels that each got.

#323 airflow: Various fixes
  reach/elastic/common.py
  reach/elastic/fulltext_docs.py
Labels: bug

#308 Reach alpha design amends
  reach/web/src/css/about.css
  reach/web/src/css/footer.css
  reach/web/src/css/header.css
  reach/web/src/css/home.css
  reach/web/src/css/search.css
  reach/web/src/css/style.css
  reach/web/src/css/variables.css
  reach/web/src/images/Icon_Scroll-arow.svg
  reach/web/src/images/Illustration_Glass.svg
  reach/web/src/images/Shape_01.svg
  reach/web/src/images/Shape_02.svg
  reach/web/src/images/Wellcome_logo.svg
  reach/web/src/images/wellcome-logo.svg
  reach/web/templates/about.html
  reach/web/templates/base.html
  reach/web/templates/how-it-works.html
  reach/web/templates/index.html
  reach/web/templates/results/citations.html
  reach/web/templates/results/policy-docs.html
  reach/web/templates/search/citations.html
  reach/web/templates/search/policy-docs.html
Labels: bug

#333 DAG data propagation issue Fix #331
  reach/airflow/tasks/fuzzy_match_refs.py
  reach/pdf_parser/pdf_parse.py
  reach/refparse/refparse.py
Labels: bug

#351 airflow: Update a logging output to reference correct key name
  reach/airflow/tasks/fuzzy_match_refs.py
Labels: bug

#376 Various fixes for the following:
  reach/airflow/dags/data_flow_testing.py
  reach/airflow/dags/policy.py
  reach/pdf_parser/pdf_parse.py
  reach/scraper/wsf_scraping/file_system.py
  reach/scraper/wsf_scraping/spiders/acme_spider.py
  reach/scraper/wsf_scraping/spiders/gov_spider.py
  reach/scraper/wsf_scraping/spiders/msf_spider.py
  reach/scraper/wsf_scraping/spiders/nice_spider.py
  reach/scraper/wsf_scraping/spiders/parliament_spider.py
  reach/scraper/wsf_scraping/spiders/unicef_spider.py
  reach/scraper/wsf_scraping/spiders/who_iris_spider.py
Labels: bug, enhancement

#377 - Adds the DocumentID as a key in the scraped PDFs metadata
  reach/scraper/wsf_scraping/items.py
  reach/scraper/wsf_scraping/pipelines.py
Labels: enhancement
